type                 = "maintenance"
name                 = "{{ .nuon.install.id }}-maintenance"
description          = "{{ .nuon.install.id }} maintenance role for nuonco/demo/aws-lambda install"
display_name         = "{{ .nuon.install.id }}-maintenance"
permissions_boundary = "./maintenance_boundary.json"

[[policies]]
managed_policy_name = "AdministratorAccess"
