type                 = "provision"
name                 = "{{.nuon.install.id}}-provision"
description          = "{{ .nuon.install.id }} provision role for nuonco/demo/aws-lambda install"
display_name         = "{{ .nuon.install.id }}-provision"
permissions_boundary = "./provision_boundary.json"

[[policies]]
managed_policy_name = "AdministratorAccess"

