#:schema https://api.nuon.co/v1/general/config-schema?source=action
name    = "alb_healthcheck"
timeout = "30s"

[[triggers]]
type = "manual"

[[steps]]
name    = "alb-healthcheck"
command = "./healthcheck.sh"

[steps.public_repo]
repo      = "sharkymark/nuon"
directory = "src/app-configs/outline/src/actions/alb"
branch    = "mm/outline"

[steps.env_vars]
INGRESS_NAME      = "{{.nuon.install.id}}-public"
INGRESS_NAMESPACE = "outline"