#:schema https://api.nuon.co/v1/general/config-schema?source=runner
runner_type     = "aws"
helm_driver     = "configmap"
init_script_url = "https://raw.githubusercontent.com/nuonco/runner/refs/heads/fd/mng-mode/updated-script/scripts/aws/init.sh#default"

[env_vars]
foo = "bar"
