#:schema https://api.nuon.co/v1/general/config-schema?source=docker_build
name   = "docker_image"
type = "docker_build"

dockerfile = "Dockerfile"

[public_repo]
repo      = "sharkymark/nuon"
directory = "src/app-config/aws-lambda/src/components/docker-image"
branch    = "mm/aws-lambda-app-config"