#:schema https://api.nuon.co/v1/general/config-schema?source=terraform
name              = "dynamodb_table"
type              = "terraform_module"
terraform_version = "1.11.4"

[public_repo]
repo      = "sharkymark/nuon"
directory = "src/app-config/aws-lambda/src/components/dynamodb-table"
branch    = "mm/mgmt-mode"

[vars]
name       = "widgets"
hash_key   = "ID"
install_id = "{{.nuon.install.id}}"
region     = "{{.nuon.install_stack.outputs.region}}"
