#:schema https://api.nuon.co/v1/general/config-schema?source=terraform
name   = "dynamodb_table"
type = "terraform_module"
dependencies = ["docker_image"]

[public_repo]
repo      = "sharkymark/nuon"
directory = "src/app-config/aws-lambda/src/components/dynamodb-table"
branch    = "mm/aws-lambda-app-config"

[[var_file]]
contents = "./1-dynamodb-table.tfvars"