#:schema https://api.nuon.co/v1/general/config-schema?source=terraform
name              = "api_gateway"
type              = "terraform_module"
terraform_version = "1.11.3"
dependencies = []

[public_repo]
repo      = "sharkymark/nuon"
directory = "src/app-config/aws-lambda/src/components/api-gateway"
branch    = "mm/aws-lambda-app-config"

[vars]
name = "api"
domain_name = "api.{{.nuon.install.sandbox.outputs.public_domain.name }}"
domain_name_certificate_arn = "{{.nuon.components.certificate.outputs.public_domain_certificate_arn}} "
lambda_function_arn = "{{.nuon.components.get_function.outputs.lambda_function_arn}}"
zone_id = "{{.nuon.install.sandbox.outputs.public_domain.zone_id}}"