#:schema https://api.nuon.co/v1/general/config-schema?source=terraform
name              = "api_gateway"
type              = "terraform_module"

[public_repo]
repo      = "sharkymark/nuon"
directory = "src/app-config/aws-lambda/src/components/api-gateway"
branch    = "mm/aws-lambda-app-config"

[vars]
name = "{{.nuon.inputs.inputs.sub_domain}}"
domain_name = "{{.nuon.inputs.inputs.sub_domain}}.{{.nuon.install.sandbox.outputs.public_domain.name }}"
domain_name_certificate_arn = "{{.nuon.components.certificate.outputs.public_domain_certificate_arn}} "
lambda_function_arn = "{{.nuon.components.lambda_function.outputs.lambda_function_arn}}"
zone_id = "{{.nuon.install.sandbox.outputs.public_domain.zone_id}}"