apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: maintenance
  namespace: default
subjects:
- kind: Group
  name: maintenance
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: maintenance
  apiGroup: rbac.authorization.k8s.io
