#:schema https://api.nuon.co/v1/general/config-schema?source=inputs
[[group]]
name         = "dns"
description  = "DNS Configrations"
display_name = "Configurations for the sub domain for Route53"

[[input]]
name         = "sub_domain"
description  = "The sub domain for the Coder service"
default      = "coder"
display_name = "Sub Domain"
group        = "dns"
