#:schema https://api.nuon.co/v1/general/config-schema?source=inputs
[[group]]
name         = "coder"
description  = "Coder Configrations"
display_name = "Configurations for the Coder Cloud Development Environment platform https://github.com/coder/coder/releases"

[[input]]
name         = "release"
description  = "The release of Coder to deploy."
default      = "v2.23.2"
display_name = "Release"
group        = "coder"

[[input]]
name         = "replicas"
description  = "The number of replicas of the Coder control plane pods to deploy"
default      = "1"
display_name = "Coder Replicas"
group        = "coder"

[[input]]
name         = "provisioners"
description  = "The number of Terraform provisioners to create and destroy workspace resources"
default      = "3"
display_name = "Terraform Provisioners"
group        = "coder"

[[input]]
name         = "telemetry"
description  = "Enable telemetry collection"
default      = "true"
display_name = "Telemetry"
group        = "coder"

[[input]]
name         = "max_token_lifetime"
description  = "Maximum lifetime of a user token for CLI and API access"
default      = "8760h0m0s"
display_name = "Token Lifetime"
group        = "coder"

[[input]]
name         = "session_duration"
description  = "Duration of a user session before requireing re-authentication"
default      = "168h0m0s"
display_name = "Session duration"
group        = "coder"

[[input]]
name         = "block_direct"
description  = "Block peer-to-peer (aka direct) workspace connections. All workspace connections from the CLI will be proxied through Coder"
default      = "false"
display_name = "Block Direct Connections"
group        = "coder"

[[group]]
name         = "compute"
description  = "How many nodes to provision to support dev environments? https://aws.amazon.com/ec2/instance-types/ e.g., t3-medium, t3.xlarge, t3.2xlarge"
display_name = "Kubernetes Nodes"
group        = "compute"

[[input]]
name         = "instance_size"
description  = "The AWS instance size to use for each node in the EKS cluster"
default      = "t3-medium"
display_name = "Node Instance Size"
group        = "compute"

[[input]]
name         = "min_size"
description  = "Minimum number of nodes to provision in the EKS cluster"
default      = "2"
display_name = "Minimum Node Count"
group        = "compute"

[[input]]
name         = "max_size"
description  = "Maximum number of nodes to provision in the EKS cluster"
default      = "5"
display_name = "Maximum Node Count"
group        = "compute"

[[input]]
name         = "desired_capacity"
description  = "Desired number of nodes to provision in the EKS cluster"
default      = "2"
display_name = "Desired Node Count"
group        = "compute"
