type        = "aws-cloudformation"
name        = "nuon-demos-eks-simple-{{.nuon.install.id}}"
description = "QuickLink to install runner for BYOC Nuon: Install {{.nuon.install.id}}"

# nested stack
vpc_nested_template_url    = "https://nuon-artifacts.s3.us-west-2.amazonaws.com/sandbox/exp/aws-cloudformation-templates/v0.1.4/vpc/eks/default/stack.yaml"
runner_nested_template_url = "https://nuon-artifacts.s3.us-west-2.amazonaws.com/sandbox/exp/aws-cloudformation-templates/v0.1.4/runner/asg/stack.yaml"
