#:schema https://api.nuon.co/v1/general/config-schema?type=terraform
name              = "certificate"
type              = "terraform_module"
terraform_version = "1.11.3"

[public_repo]
#repo      = "nuonco/example-app-configs"
#directory = "outline/src/components/certificate"
#branch    = "main"
repo      = "sharkymark/nuon"
directory = "src/app-configs/outline/src/components/certificate"
branch    = "mm/outline"

[vars]
zone_id     = "{{.nuon.install.sandbox.outputs.nuon_dns.public_domain.zone_id}}"
domain_name = "{{.nuon.install.sandbox.outputs.nuon_dns.public_domain.name}}"
subject_alternative_names = "*.{{.nuon.install.sandbox.outputs.nuon_dns.public_domain.name}}"

install_id  = "{{ .nuon.install.id }}"
region      = "{{ .nuon.install_stack.outputs.region }}"

# https://registry.terraform.io/modules/terraform-aws-modules/acm/aws/latest