#:schema https://api.nuon.co/v1/general/config-schema?type=helm
name         = "application_load_balancer"
type         = "helm_chart"
chart_name   = "application-load-balancer"
dependencies = ["outline"]

[public_repo]
#repo      = "nuonco/example-app-configs"
#directory = "outline/src/components/alb"
#branch    = "main"
repo      = "sharkymark/nuon"
directory = "src/app-config/outline/src/components/alb"
branch    = "mm/outline"

[values]
domain_certificate = "{{.nuon.components.certificate.outputs.public_domain_certificate_arn}}"
domain             = "{{.nuon.install.sandbox.outputs.nuon_dns.public_domain.name}}"

https_port         = "443"
service_name       = "outline"
service_port       = "80"
install_name       = "{{.nuon.install.id}}"
namespace          = "outline"
healthcheck_path   = "/livez"
