name         = "application_load_balancer"
type         = "helm_chart"
chart_name   = "application-load-balancer"
dependencies = ["coder"]

[public_repo]
repo      = "sharkymark/nuon"
directory = "src/app-config/coder/src/components/alb"
branch    = "main"

[values]
domain_certificate = "{{.nuon.components.base_domain_certificate.outputs.public_domain_certificate_arn}}"
domain             = "{{.nuon.install.sandbox.outputs.nuon_dns.public_domain.name}}"
additional_domain_certificates = [
    "{{.nuon.components.wildcard_base_domain_ertificate.outputs.public_domain_certificate_arn}}"
]
https_port         = "443"
service_name       = "coder"
service_port       = "80"
install_name       = "{{.nuon.install.id}}"
namespace          = "coder"
healthcheck_path   = "/livez"
