name           = "coder"
type           = "helm_chart"
chart_name     = "coder"
namespace      = "coder"
storage_driver = "configmap"
dependencies   = ["coder_db, application_load_balancer"]

[public_repo]
repo      = "coder/coder"
directory = "helm/coder"
branch    = "main"

[[values_file]]
contents = "./values/coder.yaml"
