name         = "application_load_balancer"
type         = "helm_chart"
chart_name   = "application-load-balancer"
dependencies = ["coder"]

[public_repo]
repo      = "nuonco/components"
directory = "aws/alb"
branch    = "main"

[values]
domain_certificate = "{{.nuon.components.certificate.outputs.public_domain_certificate_arn}}"
domain             = "coder.{{.nuon.install.sandbox.outputs.public_domain.name}}"
https_port         = "443"
service_name       = "coder"
service_port       = "http"
install_name       = "{{.nuon.install.id}}"
