name           = "coder_db"
type           = "helm_chart"
chart_name     = "postgresql"
namespace      = "coder"
storage_driver = "configmap"

[public_repo]
# commenting out gitnami repo for now due to size
# repo      = "gitnami/charts"
# directory = "gitnami/postgresql"
repo      = "sharkymark/nuon"
directory = "src/helm/postgresql"
branch    = "main"

[[values_file]]
contents = "./values/bitnami_postgres.yaml"