name           = "coder_db"
type           = "helm_chart"
chart_name     = "postgresql"
namespace      = "coder"
storage_driver = "configmap"

[public_repo]
repo      = "bitnami/charts"
directory = "bitnami/postgresql"
branch    = "main"

[[values_file]]
contents = "./values/bitnami_postgres.yaml"