name              = "wildcard_certificate"
type              = "terraform_module"
terraform_version = "1.10.4"

[public_repo]
repo      = "nuonco/components"
directory = "aws/certificate"
branch    = "main"

[vars]
zone_id     = ""
domain_name = "*.{{ nuon.install.sandbox.outputs.albdnsname }}"
